### PR TITLE
PD-340: Change common product names and version to global variables

### PR DESCRIPTION
**Pull request by andreipope**
Access the current version and the previous version through global variables

### CODE REVIEW

**Comment by andreipope** [comment]
@nathan-px This should be merged together with https://github.com/portworx/pxdocs-tooling/pull/34.

**Comment by nathan-px** [comment]
Let's talk about this on our 1-1. There's only one page that lists the current version, but I'd like to start using text variables for some other commonly used words, such as company name, feature names, and possibly even the product name.

**Comment by andreipope** [comment]
> Let's talk about this on our 1-1. There's only one page that lists the current version, but I'd like to start using text variables for some other commonly used words, such as company name, feature names, and possibly even the product name.

OK.

**Comment by nathan-px** [comment]
I'm going to close this PR for the time being. We can open a new PR if we decide to revisit the variables in the future.

**Pull request closed without merging**
