### PR TITLE
consolidate security information

### PR DESCRIPTION
**Pull request by andreipope**

### CODE REVIEW

**Comment by andreipope** [comment]
@lpabon @harsh-px Please review these changes. Thanks!

**Comment by andreipope** [comment]
@lpabon Just wondering, did you get a chance to review these changes? Thanks!

**Comment by vilasd** [comment]
@andreipope looks like this has conflicts. Can you fix those and reopen the PR if required ?

**Comment by andreipope** [comment]
> @andreipope looks like this has conflicts. Can you fix those and reopen the PR if required ?

@vilasd Right, probably it's easier to just close this PR and open a new one.

**Comment by andreipope** [comment]
@vilasd @nathan-px I'm having second thoughts here. This is an old PR and it overlaps with our docs reorg initiative. So my suggestion would be to just close this. What do you think?

**Comment by nathan-px** [comment]
@andreipope close it. Note your ideas on how you were going to reorganize this section in our mapping spreadsheet so we can use that input during the reorg: https://docs.google.com/spreadsheets/d/1OBvS_9MMl56_1ca5ATrXP2-dEmQLTTpCUy0p3qBTVOY/edit#gid=0

**Pull request closed without merging**
