### PR TITLE
PWX-9388: Updating px-runc options

### PR DESCRIPTION
**Pull request by zoxpx**
* refreshing the page with the latest `px-runc` options
* adding the note about `-raid <0|10>` option

### CODE REVIEW

**Comment by zoxpx** [comment]
@jrivera-px , @harsh-px -- can I get a quick review on this DOC-PR?  It's been "stewing" for a week already.

**Comment by zoxpx** [comment]
Thanks Jose -- merging the change.

**Comment by andreipope** [comment]
@zoxpx Do we need to cherry-pick this to 2.1? Or maybe to 2.0.3 as well?

**Comment by zoxpx** [comment]
@andreipope -- thanks for bringing this up.
You are right with your observation, but I'd still leave things as they are for the time being.

The reason for it is that this DOC-change is accompanied w/ another code-change, where we modified how we display the usage (we switched to using golang-templates for usage, and more) -- which probably was not very smart [on my part] to bundle the changes  :)
I'd wait a bit until our testing catches up on px-2.2, validates the code, and then cherry-pick both DOC+code changes into the px-2.1

**Comment by andreipope** [comment]
@zoxpx Gotcha. Thanks for shedding some light :)

**Pull request merged**
