### PR TITLE
fixing a few typos

### PR DESCRIPTION
**Pull request by andreipope**
fixing a few typos

### CODE REVIEW

**Comment by harsh-px** [comment]
@andreipope can you resolve the conflicts here?

**Comment by harsh-px** [comment]
@prashantsr they are andrei's suggestions for your branch. Can you review?

Once it looks good, this will merge to your branch.

**Comment by harsh-px** [comment]
@andreipope please fix the conflicts here

**Comment by prashantsr** [comment]
Reviewed and resolved conflicts

**Pull request closed without merging**
