### PR TITLE
PD-356: Part I - Moving non-markdown files under the `static` folder

### PR DESCRIPTION
**Pull request by andreipope**
PD-356: Part I - Moving non-markdown files under the `samples` folder

### CODE REVIEW

**Comment by nathan-px** [comment]
I checked the links, although I don't have a good way to know if a json file was deleted or moved that's not part of this 'part'. Theoretically, these are tested as part of the link checking.

**Comment by nathan-px** [comment]
> I checked the links, although I don't have a good way to know if a json file was deleted or moved that's not part of this 'part'. Theoretically, these are tested as part of the link checking.

@andreipope what about the files that look like they were just deleted? Are they not used?

**Comment by andreipope** [comment]
> the files that look like they were

Probably just old files that aren't used anymore. Should we merge this or ask on #px-docs first and make sure we're not breaking some other page? Like our blog. Thanks!

**Comment by nathan-px** [comment]
> > the files that look like they were
> 
> Probably just old files that aren't used anymore. Should we merge this or ask on #px-docs first and make sure we're not breaking some other page? Like our blog. Thanks!

Yeah, we should post and `@here` the px-docs channel to make sure. Are there other files that look unused? We should compile a full list before we post.

**Pull request merged**
