### PR TITLE
PWX-7975: Updated specs for the manual install of prometheus/grafana …

### PR DESCRIPTION
**Pull request by pault84**
Cherry-pick from master, current docs are out of date and do not work.

Signed-off-by: Paul <paul@portworx.com>

### CODE REVIEW

**Comment by harsh-px** [comment]
@pault84 were these specs tested? Also are they in sync with the specs at install.portworx.com?

**Comment by pault84** [comment]
They have been tested by @shailvipx and they are probably not 100% up to date but the current ones don't work

**Comment by pault84** [comment]
Actually, i take that back these are just the monitoring ones. yes they are up to date.

**Comment by harsh-px** [comment]
@pault84 can you cherry pick this to master?

Also from next time, please send PR for master and then chery-pick to release branches.

**Comment by pault84** [comment]
@harsh-px this came from master.

**Pull request merged**
