### PR TITLE
PWX-7432: Adding "Common errors" page

### PR DESCRIPTION
**Pull request by zoxpx**
* including NetworkManager vs. DNS resolution troubleshooting note

### CODE REVIEW

**Comment by zoxpx** [comment]
Replacement for https://github.com/portworx/pxdocs/pull/87  (this time, using all lowercase branch-name)

**Comment by zoxpx** [comment]
**NOTE**: Consulted w/ @gourao , and he suggested we open up a generic "common errors" page, and start accumulating such \<error\> = \<solution\> snippets.

**Comment by harsh-px** [comment]
@zoxpx what is the plan for this PR?

**Comment by zoxpx** [comment]
Re @harsh-px -- the plan was to fix the Travis build system to _not_ reject the build on branches with `PWX-####` prefix.  Our contractor did some fixing, but I'm not sure if the fix ever got applied.

**Pull request merged**
